export interface AuthResponse {
    ok: boolean;
    uid?: string;
    name?: string;
    token?: string;
    msg?: string;
}

export interface User {
    uid:   string;
    name:  string;
    token: string;
}

// Generated by https://quicktype.io

export interface ErrorResponse {
    ok:  boolean;
    msg: string;
}
